# **Chaining promises**

`.then()` and `.catch()` methods always return a promise, so we can chain multiple `.then()` calls together.

First we will create a delay function that returns a promise, the returned promise will resolve after the given
number of seconds:

```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
```

In this snippet, we are using a function to wrap our promise so that it does not execute immediately.

```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

delay(2000).then(() => console.log("Resolved after 2 seconds"));
```

The statements in the `.then()` callback will only run after `delay` resolves after two seconds.

Here is how we can chain multiple `.then()` calls:

```js
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

delay(2000)
  .then(() => {
    console.log("Resolved after 3 seconds");
    return delay(3000);
  })
  .then(() => {
    console.log("Resolved after 2 seconds");
    return delay(2000);
  })
  .then(() => {
    console.log("Resolved after 1 seconds");
    throw new Error();
  })
  .catch(() => console.log("An error has occurred..."))
  .then(() => console.log("Finished"));
```

This will resolve after 2 seconds and return a promise, that will get resolved after 3 seconds and return a new promise,
and this happens until the last promise throws an error, which will be caught in `catch` and finished in the last `then` chain.